name: main

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run main.sh
        run: bash main.sh
